server:
  port: 8080

spring:
  config:
    activate:
      on-profile: h2


  datasource:
    url: jdbc:h2:tcp://localhost/~/Blind
    username : sa
    password :
    dirver-class-name : org.h2.Driver
  # spring data jpa ??
  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  mvc:              #swagger 사용시 오류해결
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace